### ISSUE TITLE
Mini In-Game Anti-Cheat (Configurable)

### ISSUE THREAD

**Issue by 1002511** [Lubenica98/FairPlayMinecraft#127]
**Hey!** I was wondering if you could add a feature that includes auto-freezing. Basically, there would be an option in the config that allows you to automatically check someone with FPM if they exceed a specific length of measurement. Here, let me show you:

This is what the config would look like: (by default to prevent lag...)

`In-Game-AC:

    enabled: false
    auto-ban: false
    auto-check: false
    notify: false

    kill-aura:
        enabled: true
        min-length: 5

    fly:
        enabled: true
        min-seconds: 20
        min-height: 20

    speed:
       enabled: true
       min-speed: 7 #in blocks per second
       min-time: 10`

Basically, this part of the config allows you to enable a mini IN-GAME anti-cheat. Let's go through the features:

- The first three are self-explanatory.
- The "notify" Boolean makes it so if a player exceeds the specified amount, it will notify online staff about the occurrence.
- Every time someone hits another player, FMP will check whether or not the hit exceeds the amount specified in the config. If it does multiple times, the event(s) specified in the config will occur. A.k.a. banning, checking, or notifying. 
- Same thing with fly, but min-seconds states how long someone is in the air for, and min-height states how much off the ground the player is.
- Speed, same thing. Every time a player moves, FMP calculates their speed. If it exceeds the minimum limit in the config, the events occur. However; that's only if that speed stays consistent for min-time amount of seconds.
- The events occur only if the enabled Boolean is set to true.

**Hopefully this was helpful in the development of FMP, and thanks for reading! :D**

**Comment by Lubenica98** [comment]
Hello,

FPMC won't be developed into server-side anticheat. If I would add these features than the checks would be done on server-side which could lower the performance of the server. The main point of FPMC is to provide a anticheat system which is client side, so that no checks are done on the Spigot server. 
You could however do this by using some other server-side anticheat plugin and define it so when the plugin detects that a player is cheating, it will execute /fpmc check <nick> command on him to force him to run the application. 
You could also use the FPMC's API if you have access to the source code of a server-side anticheat plugin.
Thank you!
